services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: domofomka-api
    restart: always
    command: uv run granian --interface asgi src.api.app:app --host ${API_HOST} --port ${API_PORT} --workers ${WORKERS_NUM} --log --access-log
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/backend/src
      - ./codes.db:/backend/codes.db
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:${API_PORT}/version
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s

  vkbot:
    build:
      context: .
      dockerfile: Dockerfile.vkbot
    container_name: domofomka-vkbot
    restart: always
    command: uv run python -m src.vkbot.main
    env_file:
      - .env
    volumes:
      - ./src:/backend/src
      - ./start_message.txt:/backend/start_message.txt
    depends_on:
      api:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:8.4-alpine
    container_name: domofomka-redis
    restart: always
    env_file:
      - .env
    hostname: ${REDIS_HOST}
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3
